---
apiVersion: v1
kind: Service
metadata:
  name: monocle
  annotations:
    domainName: "staging-monocle.crowdtap.com"
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-east-1:535700620794:certificate/38338ab7-3bce-4470-a4ae-ee948a89ff3f
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
  labels:
    app: monocle
    dns: route53
spec:
  type: LoadBalancer
  ports:
    - name: https
      protocol: TCP
      port: 443
      targetPort: 80
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: monocle
